package pipelinegen

import (
	"strings"
)

// secretPreamble is prepended to a step that runs under
// `oberth secretstore exec`.
//
// The store mounts one directory per secret and writes each KV field verbatim,
// so the value is at $OBERTH_SECRETSTORE_DIR/<secret>/<field>. The path is
// found rather than reconstructed: reconstructing it hardcodes both the
// secret's name and the field's, and a rename then produces an empty variable
// and a build that fails somewhere else entirely.
const secretPreamble = `token_file="$(find "$OBERTH_SECRETSTORE_DIR" -type f -name token -print 2>/dev/null | head -n 1)"
if [ -z "${token_file:-}" ]; then
  echo "no token was delivered under $OBERTH_SECRETSTORE_DIR" >&2
  echo "check the grant: the declared secret path must be allowed for this repository" >&2
  exit 1
fi
GITHUB_TOKEN="$(cat "$token_file")"
OBERTH_UPSTREAM_TOKEN="$GITHUB_TOKEN"
NPM_TOKEN="$GITHUB_TOKEN"
export GITHUB_TOKEN OBERTH_UPSTREAM_TOKEN NPM_TOKEN`

func render(project Project, steps []step, result Result) string {
	var out strings.Builder

	writeHeader(&out, project, result)

	out.WriteString("apiVersion: argoproj.io/v1alpha1\n")
	out.WriteString("kind: Workflow\n")
	out.WriteString("metadata:\n")
	out.WriteString("  annotations:\n")
	out.WriteString("    # Scheduler tier, not per-container resources. Those are on each template.\n")
	out.WriteString("    oberth.ci/size: M\n")
	if result.SecretPath != "" {
		out.WriteString("    # Declared here and checked against this repository's grants at admission.\n")
		out.WriteString("    # Without a matching grant the whole run is refused before any pod starts:\n")
		out.WriteString("    #   " + result.GrantCommand + "\n")
		out.WriteString("    oberth.ci/secret-paths: " + result.SecretPath + "\n")
	}
	out.WriteString("spec:\n")
	out.WriteString("  entrypoint: ci\n")
	out.WriteString("  activeDeadlineSeconds: 3600\n\n")
	out.WriteString("  volumeClaimTemplates:\n")
	out.WriteString("  - metadata:\n")
	out.WriteString("      name: work\n")
	out.WriteString("    spec:\n")
	out.WriteString(`      accessModes: ["ReadWriteOnce"]` + "\n")
	out.WriteString("      resources:\n")
	out.WriteString("        requests:\n")
	out.WriteString("          storage: 10Gi\n\n")
	out.WriteString("  templates:\n\n")

	// The chain. Each element of `steps` is its own sequential group, so a red
	// step stops the run instead of letting its siblings finish first.
	out.WriteString("  # Sequential chain, deliberately not a DAG: Argo lets the siblings of a\n")
	out.WriteString("  # failed DAG task run to completion, so a red lint would keep the whole\n")
	out.WriteString("  # test suite running and report minutes after it knew the answer.\n")
	out.WriteString("  - name: ci\n")
	out.WriteString("    steps:\n")
	for _, one := range steps {
		out.WriteString("    - - name: " + one.name + "\n")
		out.WriteString("        template: " + one.name + "\n")
	}
	out.WriteString("\n")

	for _, one := range steps {
		writeTemplate(&out, project, one, result.SecretPath)
	}
	return out.String()
}

func writeHeader(out *strings.Builder, project Project, result Result) {
	out.WriteString("# Oberth CI pipeline, generated by `oberth init`.\n#\n")
	if !result.Complete {
		out.WriteString("# THIS PIPELINE IS NOT FINISHED AND WILL FAIL ON PURPOSE.\n")
		out.WriteString("# `oberth init` could not tell how this repository is built, so rather than\n")
		out.WriteString("# emitting steps that pass by doing nothing, it emitted one step that fails\n")
		out.WriteString("# and says so. Replace the `unfinished` step below with the real build.\n#\n")
	}
	if len(project.Sources) > 0 {
		out.WriteString("# What this was generated from:\n")
		for _, line := range project.Sources {
			out.WriteString("#   - " + line + "\n")
		}
		out.WriteString("#\n")
	}
	if len(project.Untranslated) > 0 {
		out.WriteString("# What was NOT translated. Read this before trusting a green run:\n")
		for _, line := range project.Untranslated {
			out.WriteString(wrapComment(line))
		}
		out.WriteString("#\n")
	}
	if project.OriginOrg != "" && project.Org != "" && project.OriginOrg != project.Org {
		out.WriteString("# Note: this repository's origin remote suggests the org is `" + project.OriginOrg + "`,\n")
		out.WriteString("# and the server has `" + project.Org + "` registered. The registered one is what\n")
		out.WriteString("# admission matches a secret path against, so it is the one used here.\n#\n")
	}
	if result.SecretPath != "" {
		out.WriteString("# This pipeline declares a secret. Grant it once, before the first push:\n")
		out.WriteString("#\n#   " + result.GrantCommand + "\n#\n")
	}
	out.WriteString("# Images are pinned by digest, because a tag can be moved between\n")
	out.WriteString("# admission and the node pull. Refresh digest: crane digest <image>\n#\n")
	out.WriteString("# Steps run in order and stop at the first red:\n#\n#   ")
	out.WriteString(strings.Join(result.Steps, " -> "))
	out.WriteString("\n#\n")
}

// wrapComment breaks one note across comment lines at a readable width.
func wrapComment(line string) string {
	return wrapCommentAt("#   - ", "#     ", line)
}

// wrapCommentAt is the same, at a caller-chosen indent, so a comment attached
// to a template lines up with the template rather than with the file header.
func wrapCommentAt(prefix, continuation, line string) string {
	const width = 72
	var out strings.Builder
	current := prefix
	for _, word := range strings.Fields(line) {
		if len(current)+1+len(word) > width && strings.TrimSpace(current) != strings.TrimSpace(prefix) {
			out.WriteString(strings.TrimRight(current, " ") + "\n")
			current = continuation
		}
		if strings.HasSuffix(current, " ") {
			current += word
		} else {
			current += " " + word
		}
	}
	out.WriteString(strings.TrimRight(current, " ") + "\n")
	return out.String()
}

func writeTemplate(out *strings.Builder, project Project, one step, secretPath string) {
	if one.comment != "" {
		out.WriteString(wrapCommentAt("  # ", "  #   ", "["+one.name+"] "+one.comment))
	}
	out.WriteString("  - name: " + one.name + "\n")
	out.WriteString("    container:\n")
	out.WriteString(`      image: "` + one.image + `"` + "\n")
	out.WriteString("      workingDir: " + buildDir + "\n")

	script := one.script
	if one.secret && secretPath != "" {
		script = injectPreamble(script)
	}

	if one.secret && secretPath != "" {
		out.WriteString(`      command: ["` + oberthBinary + `"]` + "\n")
		out.WriteString("      args:\n")
		out.WriteString(`      - "secretstore"` + "\n")
		out.WriteString(`      - "exec"` + "\n")
		out.WriteString(`      - "--dir=` + secretsDir + `"` + "\n")
		out.WriteString(`      - "--path=` + secretPath + `"` + "\n")
		out.WriteString(`      - "--"` + "\n")
		out.WriteString(`      - "/bin/sh"` + "\n")
		out.WriteString(`      - "-c"` + "\n")
	} else {
		out.WriteString(`      command: ["/bin/sh"]` + "\n")
		out.WriteString("      args:\n")
		out.WriteString(`      - "-c"` + "\n")
	}
	out.WriteString("      - |\n")
	for _, line := range strings.Split(script, "\n") {
		if line == "" {
			out.WriteString("\n")
			continue
		}
		out.WriteString("        " + line + "\n")
	}

	out.WriteString("      env:\n")
	for _, variable := range environment(project) {
		out.WriteString("      - name: " + variable.name + "\n")
		out.WriteString(`        value: "` + variable.value + `"` + "\n")
	}

	out.WriteString("      volumeMounts:\n")
	for _, mount := range []struct{ path, subPath string }{
		{buildDir, "build"},
		{"/work/cache", "cache"},
		{"/work/home", "home"},
	} {
		out.WriteString("      - name: work\n")
		out.WriteString("        mountPath: " + mount.path + "\n")
		out.WriteString("        subPath: " + mount.subPath + "\n")
	}

	out.WriteString("      resources:\n")
	out.WriteString("        requests:\n")
	out.WriteString(`          cpu: "2"` + "\n")
	out.WriteString(`          memory: "4Gi"` + "\n")
	out.WriteString("        limits:\n")
	out.WriteString(`          cpu: "2"` + "\n")
	out.WriteString(`          memory: "4Gi"` + "\n\n")
}

// injectPreamble puts the token lookup directly after `set -eu`, so the step
// body can assume the variables are exported.
func injectPreamble(script string) string {
	lines := strings.SplitN(script, "\n", 2)
	if len(lines) == 1 {
		return script + "\n" + secretPreamble
	}
	return lines[0] + "\n" + secretPreamble + "\n" + lines[1]
}

type variable struct{ name, value string }

// environment is the same for every step of one pipeline. HOME is on the run
// volume because npm and Maven both write into it and the image's home is not
// guaranteed writable; the caches live beside it so a later step reuses what
// an earlier one downloaded.
func environment(project Project) []variable {
	common := []variable{
		{"CI", "true"},
		{"HOME", "/work/home"},
		{"GIT_TERMINAL_PROMPT", "0"},
	}
	switch project.Kind {
	case KindNode:
		return append(common,
			variable{"npm_config_cache", "/work/cache/npm"},
			variable{"npm_config_update_notifier", "false"},
			variable{"NODE_OPTIONS", "--max-old-space-size=4096"},
		)
	case KindMaven:
		return append(common,
			variable{"MAVEN_OPTS", "-Xmx3g"},
		)
	case KindGo:
		return append(common,
			variable{"GOMODCACHE", "/work/cache/gomod"},
			variable{"GOCACHE", "/work/cache/gobuild"},
			variable{"GOTOOLCHAIN", "local"},
		)
	default:
		return common
	}
}
