package main

// buildYAMLDemo is the pipeline `oberth init` used to write for every
// repository: a DAG that copies a file, checksums it, and goes green. It is
// kept here as a TEST FIXTURE only, because several validate tests need one
// known-admissible document and this one is already known to be exactly that.
//
// It is deliberately not reachable from any command. A repository that gets
// this document learns nothing about whether it builds, which is why the
// generator now emits the repository's own steps or an honest scaffold.
const buildYAMLDemo = `# Oberth CI pipeline -- generated by 'oberth init'.
#
# A demo DAG pipeline showcasing parallel execution, fan-out, and fan-in.
# Customize these steps for your project after the first run.
#
# DAG:
#
#   fetch ──┬── analyze ──┐
#           │             ├── report
#           └── validate ─┘
#                  │
#                  └── notify
#
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    # Scheduler concurrency tier:
    #   S  -- lightweight (6 concurrent)
    #   M  -- standard (3 concurrent, default)
    #   L  -- heavy (2 concurrent)
    #   XL -- exclusive (runs alone)
    # Does NOT set per-container CPU/memory — declare resources:
    # on each template. Max per-container: cpu 8, memory 16Gi.
    oberth.ci/size: S
spec:
  entrypoint: ci
  activeDeadlineSeconds: 300

  volumeClaimTemplates:
  - metadata:
      name: work
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 64Mi

  templates:

  - name: ci
    dag:
      tasks:
      - name: fetch
        template: fetch
      - name: analyze
        template: analyze
        depends: fetch
      - name: validate
        template: validate
        depends: fetch
      - name: report
        template: report
        depends: "analyze && validate"
      - name: notify
        template: notify
        depends: validate

  - name: fetch
    container:
      # Refresh digest: crane digest debian:trixie-slim
      image: debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258
      command: [/bin/sh]
      args:
      - -c
      - |
        set -e
        mkdir -p /work/artifacts
        cp /work/src/README.md /work/artifacts/source.txt 2>/dev/null \
          || echo "Hello from Oberth" > /work/artifacts/source.txt
        sha256sum /work/artifacts/source.txt > /work/artifacts/checksum.txt
        echo "fetch: $(cut -d' ' -f1 /work/artifacts/checksum.txt)"
      volumeMounts:
      - name: work
        mountPath: /work
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  - name: analyze
    container:
      # Refresh digest: crane digest debian:trixie-slim
      image: debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258
      command: [/bin/sh]
      args:
      - -c
      - |
        set -e
        f=/work/artifacts/source.txt
        printf '{"lines":%d,"words":%d,"bytes":%d,"sha256":"%s"}\n' \
          "$(wc -l <"$f")" "$(wc -w <"$f")" "$(wc -c <"$f")" \
          "$(cut -d' ' -f1 /work/artifacts/checksum.txt)" > /work/artifacts/summary.json
        echo "analyze: $(cat /work/artifacts/summary.json)"
      volumeMounts:
      - name: work
        mountPath: /work
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  - name: validate
    container:
      # Refresh digest: crane digest debian:trixie-slim
      image: debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258
      command: [/bin/sh]
      args:
      - -c
      - |
        set -e
        sha256sum -c /work/artifacts/checksum.txt
        echo "validate: all checks passed"
      volumeMounts:
      - name: work
        mountPath: /work
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  - name: report
    container:
      # Refresh digest: crane digest debian:trixie-slim
      image: debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258
      command: [/bin/sh]
      args:
      - -c
      - |
        set -e
        cat /work/artifacts/summary.json
        echo "report: fan-in complete (analyze + validate done)"
      volumeMounts:
      - name: work
        mountPath: /work
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  - name: notify
    container:
      # Refresh digest: crane digest debian:trixie-slim
      image: debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258
      command: [/bin/sh]
      args:
      - -c
      - |
        echo "notify: pipeline succeeded (${OBERTH_REF:-unknown} @ ${OBERTH_SHA:-unknown})"
      volumeMounts:
      - name: work
        mountPath: /work
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
`
