{{- if .Values.secretCreatePolicy.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: {{ include "oberth.fullname" . }}-secret-prefix
  labels:
    {{- include "oberth.labels" . | nindent 4 }}
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["secrets"]
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Release.Namespace }}
  matchConditions:
    - name: created-by-oberth-sa
      expression: >-
        request.userInfo.username == 'system:serviceaccount:{{ .Release.Namespace }}:{{ include "oberth.serviceAccountName" . }}'
  validations:
    - expression: >-
        object.metadata.name.startsWith('oberth-release-')
      message: "Oberth service account may only create Secrets with the 'oberth-release-' prefix"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: {{ include "oberth.fullname" . }}-secret-prefix
  labels:
    {{- include "oberth.labels" . | nindent 4 }}
spec:
  policyName: {{ include "oberth.fullname" . }}-secret-prefix
  validationActions:
    - Deny
{{- end }}
