apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oberth.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oberth.labels" . | nindent 4 }}
automountServiceAccountToken: true
