{{- if .Values.upstream.createSecrets }}
{{- $privateName := .Values.upstream.keySecret -}}
{{- $privateExisting := lookup "v1" "Secret" .Release.Namespace $privateName -}}
{{- $knownHostsName := .Values.upstream.knownHostsSecret -}}
{{- $knownHostsExisting := lookup "v1" "Secret" .Release.Namespace $knownHostsName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $privateName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "oberth.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $privateExisting }}
  {{- toYaml $privateExisting.data | nindent 2 }}
  {{- else }} {}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $knownHostsName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "oberth.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $knownHostsExisting }}
  {{- toYaml $knownHostsExisting.data | nindent 2 }}
  {{- else }} {}
  {{- end }}
{{- end }}
